sudo: required
language: python
python:
  - "3.6"
services:
  - docker
git:
  depth: 1
  submodules: false
env:
  - BUILD=ubuntu:xenial
  - BUILD=ubuntu:bionic
  - BUILD=ubuntu:focal
  - BUILD=ubuntu:groovy
  - BUILD=3ds
  - BUILD=vita
  - BUILD=wii
  - BUILD=switch
  - BUILD=wasm
install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
script:
  - travis_wait 60 ./buildscripts/docker-build.sh -q $BUILD
