sudo: required
language: python
python:
  - "3.6"
services:
  - docker
git:
  depth: 1
  submodules: false
env:
  - BUILDS=ubuntu:xenial
  - BUILDS=ubuntu:bionic
  - BUILDS=3ds
  - BUILDS=vita
  - BUILDS=wii
  - BUILDS=switch
install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - pip install docker-squash
script:
  - |
    for build in $BUILDS; do
      travis_wait 60 ./buildscripts/docker-build.sh -q $build || exit 1
    done
