sudo: required
services:
  - docker
git:
  depth: 1
  submodules: false
env:
  - BUILDS=ubuntu:xenial
  - BUILDS=ubuntu:artful
  - BUILDS=ubuntu:bionic
  - BUILDS=3ds
  - BUILDS=vita
  - BUILDS=wii
  - BUILDS=switch
install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - pip install --user docker-squash docker\<3
script:
  - |
    for build in $BUILDS; do
      echo "Building $build"
      DOCKERFILE=dockerfiles/$(echo $build | sed -e 's/:/-/')/Dockerfile
      (travis_wait 60 docker build -q -t mgba/$build . -f $DOCKERFILE &&
        docker-squash mgba/$build -f $(head -n1 $DOCKERFILE | cut -d ' ' -f2) -t mgba/$build &&
        docker push mgba/$build) || exit 1
    done
